---jsonb_build_object. jsonb_agg use case demo.
/*
jsonb_build_object ( VARIADIC "any" ) → jsonb
Builds a JSON object out of a variadic argument list.
By convention, the argument list consists of alternating keys and values.
Key arguments are coerced to text; value arguments are converted as per to_json or to_jsonb.
*/
---set up the test table.
begin;
create temp table test(test_id int GENERATED by default AS IDENTITY, col_a text, col_b text, col_c text);
insert into test(col_a, col_b, col_c) values('a', 'string1','stringa');
insert into test(col_a, col_b, col_c) values('b', 'string2','stringa2');
insert into test(col_a, col_b, col_c) values('a', 'string3','stringa3');
insert into test(col_a, col_b, col_c) values('b', 'string4','stringa4');
insert into test(col_a, col_b, col_c) values('a', 'string5','stringa5');
commit;
----------------------------------------------
--jsonb_agg: PCollects all the input values, including nulls, into a JSONB array.
    --Values are converted to JSON as per to_json or to_jsonb.
SELECT col_a, jsonb_agg(
    jsonb_build_object('col_b', col_b
                   , 'col_c' , col_c)) AS jsonbagg
FROM   test
GROUP  BY col_a;
-----